### ISSUE TITLE
libmain2.a error

### ISSUE THREAD

**Issue by tmmsunny012** [LongHairedHacker/rboot-arduino-ota#1]
Hi  i tried to  compile it but libmain2.a file is missing it is saying

ld: cannot find -lmain2
collect2: error: ld returned 1 exit status
Makefile:95: recipe for target 'build/rom.elf' failed
make: *** [build/rom.elf] Error 1
 
can you suugest how to solve this

**Comment by LongHairedHacker** [comment]
Firstly, as this code is an unmaintained proof of concept,
I wouldn't expect it to work at all with any recent iteration of the ardiuno runtime or the esp sdk. 
It was since incorporated in https://github.com/entropia/gpn17-badge-esp8266-arduino and is maintained there.
Be aware that the larger repo is specifically intended for the gpn17-badge and may not produce useable binaries for at all.

Secondly, libmain2.a is patched version of the esp-sdks libmain.a
The rboot makefiles should show you how to generate it. 
See https://github.com/LongHairedHacker/rboot/blob/e0b67d9071eb5a557aea7fdaf1667a4444ee73bd/testroms/Makefile#L58
Please be aware that additional patches to the arduino libs are require to make the wifi work again,
as one of the rom slots overwrites the wifi configuration.
I nerver had these patches as I do not use arduino and as this repo is just a proof of concept for booting ardiuno code using rboot.

**Comment by tmmsunny012** [comment]
thanks for the links.
